### ISSUE TITLE
Organization account statics

### ISSUE THREAD

**Issue by clarkzjw** [numbbbbb/githuber.info#4]
![qq 20150105235538](https://cloud.githubusercontent.com/assets/2663319/5615439/4a14d56a-9536-11e4-8762-87f16351107f.jpg)
- 每周动态，每日动态这些应该都是可以做的吧。
- 不过对于组织来说，star可能不太现实。。。:smiley:

**Comment by numbbbbb** [comment]
非常感谢你的建议，我们正在做org的统计，敬请期待~
